### PR TITLE
Update for SublimeLinter 4 API.

### PR DESCRIPTION
**Pull request by ChrisCummins**
github.com/ckaznocha/SublimeLinter-contrib-write-good/issues/14
github.com/ckaznocha/SublimeLinter-contrib-write-good/issues/11

### CODE REVIEW

**Comment by ChrisCummins** [comment]
Note the reason for the failing test is he travis config is 404ing on some old python URL.

**Comment by dillonma** [comment]
@ChrisCummins would love to have this fix and have it back in the package repository -- any updates?

**Comment by MatissJanis** [comment]
Any progress here? Would love to bring this package back to life.

**Comment by ChrisCummins** [comment]
Sorry folks I had a busy couple of weeks. I've merged this into master and will push the update to Package Control.

**Comment by MatissJanis** [comment]
Thanks so much @ChrisCummins ! Upgraded and it works like a charm!

**Comment by ChrisCummins** [comment]
Fab! Glad to hear :)

**Comment by ckaznocha** [comment]
🙏 Great work @ChrisCummins!

**Pull request merged**
